env:
  browser: true
  es6: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 6

plugins: [ "import" ]

rules:
  # Possible Errors
  # https://github.com/eslint/eslint/tree/master/docs/rules#possible-errors
  no-control-regex: 2
  no-console: 1
  no-debugger: 2
  no-dupe-args: 2
  no-dupe-keys: 2
  no-duplicate-case: 2
  no-empty-character-class: 2
  no-ex-assign: 2
  no-extra-boolean-cast : 2
  no-extra-semi: 2
  no-invalid-regexp: 2
  no-irregular-whitespace: 1
  no-proto: 2
  no-unexpected-multiline: 2
  no-unreachable: 2
  valid-typeof: 2

  # Best Practices
  # https://github.com/eslint/eslint/tree/master/docs/rules#best-practices
  no-fallthrough: 2
  no-redeclare: 2

  # Stylistic Issues
  # https://github.com/eslint/eslint/tree/master/docs/rules#stylistic-issues
  comma-spacing: 2
  eol-last: 2
  keyword-spacing: 2
  max-len: [1, 160, 2]
  new-parens: 2
  no-mixed-spaces-and-tabs: 2
  no-multiple-empty-lines: [2, {max: 2}]
  no-trailing-spaces: 2

  # JSX
  jsx-quotes: [2, "prefer-double"]

  # Import
  import/no-unresolved: [1, {"commonjs": true, "amd": true}]
  import/export: 2

  # Variables
  # https://github.com/eslint/eslint/tree/master/docs/rules#variables
  no-undef: 2

# Global scoped method and vars
globals:
  __dirname: true
  require: true
  process: true
  ENV: true
  module: true
