---
title: 'Visualizing Data For Regression'
author: 'John'
date: '2020-06-23'
output: html_document
---

```{r setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## Import packages
library(ggplot2)
library(repr)
library(hexbin)
library(GGally) ## Adds pair-wise scatter plots to ggplot2
options(repr.plot.width=4, repr.plot.height=4) # Set the initial plot area dimensions
```

## Visualizing Data For Regression


```{r auto_prices}

read.auto <- function(file = 'Automobile price data _Raw_.csv'){
    ## Read the csv file
    auto.price <- read.csv(file, header = TRUE, stringsAsFactors = FALSE)

    numcols <- switch(
      as.character((!exists("numcols") || is.na(numcols) || is.null(numcols))[1]), 
      "TRUE" = { # if numcols does not exist or is not populated ("TRUE"), 
        # use these defaults:
        c('price', 'bore', 'stroke', 'horsepower', 'peak.rpm')
      }, # else use existing values
      numcols)
    print(c("numeric columns:", numcols))
    
    for(col in c('price', 'bore', 'stroke', 'horsepower', 'peak.rpm')){
        for (idx in (1:length(auto.price[,col]))) {
          temp = auto.price[idx,col]
          if (temp == '?' || is.na(auto.price[idx,col])) {
            # Convert ? to NA
            auto.price[idx,col] = ifelse(temp == '?', NA, auto.price[idx,col])
            print(c(col, idx, auto.price[idx,col]))
          }
        }
      
        ## Coerce some character columns to numeric
        auto.price[,col] = as.numeric(auto.price[,col])
    }

    ## Remove cases or rows with missing values. 
    ## Keep the rows which do not have NAs. 
    auto.price = auto.price[complete.cases(auto.price[, numcols]), ]
    
    ## Drop some unneeded columns
    auto.price[,'symboling'] = NULL
    auto.price[,'normalized.losses'] = NULL
    
    return(auto.price)
}

cat_cols <- c('fuel.type', 'aspiration', 'num.of.doors', 'body.style', 
            'drive.wheels', 'engine.location', 'engine.type', 'num.of.cylinders')

plotcols <- c('price', 'city.mpg', 'curb.weight', 'engine.size', 'horsepower', 'fuel.type')

auto_prices <- read.auto()
print("all auto columns:")
colnames(auto_prices)
```

```{r explore}
head(auto_prices)

str(auto_prices)

summary(auto_prices)
```

```{r bar_charts}
plot_bars <- function(df){
    options(repr.plot.width=4, repr.plot.height=3.5) # Set the initial plot area dimensions
  
    print("character columns:")
    for(col in colnames(df)){
        if(is.character(df[,col])){
            print(col)
            p <- ggplot(df, aes_string(col)) + 
                       geom_bar(alpha = 0.6) + 
                       theme(axis.text.x = element_text(angle = 90, hjust = 1))
            print(p)
        }
    }
}

plot_bars(auto_prices)
```

```{r kernel_density_charts}
plot_dist <- function(df, plotcols){
    options(repr.plot.width=4, repr.plot.height=3) # Set the initial plot area dimensions
    for(col in plotcols){
        #if(is.numeric(df[,col])){
            p <- ggplot(df, aes_string(col)) + 
                       geom_density(color = 'blue') +
                       geom_rug()
            print(p)
        #}
    }
}

plot_dist(auto_prices, plotcols)
```

```{r scatter_plots}
plot_scatter_t <- function(df, cols, col_y = 'price', alpha = 1.0){
    options(repr.plot.width=4, repr.plot.height=3.5) # Set the initial plot area dimensions
    for(col in cols){
        p <- ggplot(df, aes_string(col, col_y)) + 
                   geom_point(alpha = alpha) +
                   ggtitle(paste('Scatter plot of', col_y, 'vs.', col))
        print(p)
    }
}

plot_scatter_t(auto_prices, plotcols, alpha = 0.2)
```

```{r hex_bin_charts}
plot_hex <- function(df, cols, col_y = 'price', bins = 30){
    options(repr.plot.width=4, repr.plot.height=3.5) # Set the initial plot area dimensions
    for(col in cols){
        p <- ggplot(df, aes_string(col, col_y)) + 
                   geom_hex(show.legend = TRUE, bins = bins) +
                   ggtitle(paste('2-D hexbin plot of', col_y, 'vs.', col))
        print(p)
    }
}

plot_hex(auto_prices, plotcols, bins = 10)
```

```{r box_plots}
plot_box <- function(df, cols, col_y = 'price'){
    options(repr.plot.width=4, repr.plot.height=3.5) # Set the initial plot area dimensions
    for(col in cols){
        p <- ggplot(df, aes_string(col, col_y)) + 
                   geom_boxplot() +
                   ggtitle(paste('Box plot of', col, 'vs.', col_y))
        print(p)
    }
}

plot_box(auto_prices, cat_cols)
```

```{r violin_plots}
plot_violin <- function(df, cols, col_y = 'price', bins = 30){
    options(repr.plot.width=4, repr.plot.height=3.5) # Set the initial plot area dimensions
    for(col in cols){
        p <- ggplot(df, aes_string(col, col_y)) + 
                   geom_violin() +
                   ggtitle(paste('Violin plot of', col, 'vs.', col_y))
        print(p)
    }
}

plot_violin(auto_prices, cat_cols)
```
```{r marker_shapes}
plot_scatter_sp <- function(df, cols, col_y = 'price', alpha = 1.0){
    options(repr.plot.width=5, repr.plot.height=3.5) # Set the initial plot area dimensions
    for(col in cols){
        p <- ggplot(df, aes_string(col, col_y)) + 
                   geom_point(aes(shape = factor(fuel.type)), alpha = alpha) +
                   ggtitle(paste('Scatter plot of', col_y, 'vs.', col, '\n with shape by fuel type'))
        print(p)
    }
}

plot_scatter_sp(auto_prices, plotcols, alpha = 0.2)
```

```{r marker_sizes}
plot_scatter_sp_sz = function(df, cols, col_y = 'price', alpha = 1.0){
    options(repr.plot.width=5, repr.plot.height=3.5) # Set the initial plot area dimensions
    df$curb.weight.2 = df$curb.weight**2
    for(col in cols){
        p = ggplot(df, aes_string(col, col_y)) + 
                   geom_point(aes(shape = factor(fuel.type), size = curb.weight.2), alpha = alpha) +
                   ggtitle(paste('Scatter plot of', col_y, 'vs.', col, '\n with shape by fuel type'))
        print(p)
    }
}

plot_scatter_sp_sz(auto_prices, plotcols, alpha = 0.1)
```

```{r marker_colors}
plot_scatter_sp_sz_cl = function(df, cols, col_y = 'price', alpha = 1.0){
    options(repr.plot.width=5, repr.plot.height=3.5) # Set the initial plot area dimensions
    df$curb.weight.2 = df$curb.weight**2
    for(col in cols){
        p = ggplot(df, aes_string(col, col_y)) + 
                   geom_point(aes(shape = factor(fuel.type), size = curb.weight.2, color = aspiration), 
                              alpha = alpha) +
                   ggtitle(paste('Scatter plot of', col_y, 'vs.', col, 
                                 '\n with shape by fuel type',
                                 '\n and color by aspiration'))
        print(p)
    }
}

plot_scatter_sp_sz_cl(auto_prices, plotcols, alpha = 0.2)
```
```{r pair_wise_scatter_plots}
options(repr.plot.width=6, repr.plot.height=6) # Set the initial plot area dimensions
plot_ggp <- ggpairs(auto_prices,
      columns = plotcols,
      aes(color = fuel.type, alpha = 0.1),
      lower = list(continuous = wrap("points", alpha = 0.3), combo = wrap("facethist", binwidth=0.8)),
      upper = list(continuous = ggally_density, combo = wrap("box")),
      progress = FALSE)
```
```{r render, echo=FALSE, fig.width=14, fig.height=14}
options(warn = -1)
print(plot_ggp)
```

